# HID keymaps
# - Values may be hex ("0x28") or decimal (40)
# - Keys are matched case-insensitively

keyboard:
  # control & navigation
  enter: 0x28
  space: 0x2C
  esc: 0x29
  backspace: 0x2A
  tab: 0x2B
  left: 0x50
  right: 0x4F
  up: 0x52
  down: 0x51
  page_up: 0x4B
  page_down: 0x4E
  home: 0x4A

  # digits (top row)
  n_1: 0x1E
  n_2: 0x1F
  n_3: 0x20
  n_4: 0x21
  n_5: 0x22
  n_6: 0x23
  n_7: 0x24
  n_8: 0x25
  n_9: 0x26
  n_0: 0x27

  # letters
  a: 0x04
  b: 0x05
  c: 0x06
  d: 0x07
  e: 0x08
  f: 0x09
  g: 0x0A
  h: 0x0B
  i: 0x0C
  j: 0x0D
  k: 0x0E
  l: 0x0F
  m: 0x10
  n: 0x11
  o: 0x12
  p: 0x13
  q: 0x14
  r: 0x15
  s: 0x16
  t: 0x17
  u: 0x18
  v: 0x19
  w: 0x1A
  x: 0x1B
  y: 0x1C
  z: 0x1D

  # function keys
  f1: 0x3A
  f2: 0x3B
  f3: 0x3C
  f4: 0x3D
  f5: 0x3E
  f6: 0x3F
  f7: 0x40
  f8: 0x41
  f9: 0x42
  f10: 0x43
  f11: 0x44
  f12: 0x45

consumer_usages:
  # transport
  play_pause: 0x00CD
  stop: 0x00B7
  scan_next: 0x00B5
  scan_prev: 0x00B6
  fast_fwd: 0x00B3
  rewind: 0x00B4

  # volume
  muting: 0x00E2
  vol_inc: 0x00E9
  vol_dec: 0x00EA

  # menu/navigation (Apple/tvOS)
  ac_home: 0x0223
  ac_back: 0x0224
  menu: 0x0040
  menu_pick: 0x0041
  menu_up: 0x0042
  menu_down: 0x0043
  menu_left: 0x0044
  menu_right: 0x0045

  # misc
  power: 0x0030
  ch_up: 0x009C
  ch_down: 0x009D
  guide: 0x008D
  red: 0x0069
  green: 0x006A
  yellow: 0x006C
  blue: 0x006B
  subtitles: 0x0061
  record: 0x00B2