# Button mapping for Harmony Remote

device:
  by_id: "/dev/input/by-id/usb-Logitech_USB_Receiver-if02-event-kbd"
  grab: true

mapping:
  786924: rem_power_off
  786920: rem_activity_1
  786925: rem_activity_2
  786921: rem_activity_3
  786935: rem_red
  786934: rem_green
  786933: rem_yellow
  786932: rem_blue
  786943: rem_info
  KEY_LEFT: rem_dir_left
  KEY_RIGHT: rem_dir_right
  KEY_UP: rem_dir_up
  KEY_DOWN: rem_dir_down
  KEY_KPENTER: rem_ok
  KEY_ENTER: rem_enter
  KEY_BACK: rem_back
  KEY_EXIT: rem_exit
  KEY_COMPOSE: rem_menu
  KEY_REWIND: rem_rewind
  KEY_PLAY: rem_play
  KEY_FASTFORWARD: rem_fast_fwd
  KEY_RECORD: rem_record
  KEY_PAUSE: rem_pause
  KEY_STOPCD: rem_stop
  KEY_VOLUMEUP: rem_vol_up
  KEY_VOLUMEDOWN: rem_vol_down
  KEY_MUTE: rem_mute
  KEY_CHANNELUP: rem_ch_up
  KEY_CHANNELDOWN: rem_ch_down
  KEY_PVR: rem_dvr
  KEY_PROGRAM: rem_guide
  KEY_0: rem_0
  KEY_1: rem_1
  KEY_2: rem_2
  KEY_3: rem_3
  KEY_4: rem_4
  KEY_5: rem_5
  KEY_6: rem_6
  KEY_7: rem_7
  KEY_8: rem_8
  KEY_9: rem_9
  KEY_KPMINUS: rem_hyphen
