room: "xxxxxx"

bt:
  enabled: true
  device_name: "PiHub-xxxxx"

mqtt:
  host: "192.168.70.24"
  port: 1883
  prefix_bridge: "pihub/xxxxxx"
  username: "remote"
  password: "remote"

pyatv:
  enabled: false
  address:   "192.168.70.xx"
  identifier: ""
  companion: ""                # paste Companion creds if you have them
  airplay:   ""                  # paste AirPlay creds if you have them
